development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: url: redis://redistogo:d0ed635634356d4408c1effb00bc9493@hoki.redistogo.com:9247/
  channel_prefix: message_me_production
